import Head from "next/head";
import Image from "next/image";
import { useContext, useState } from "react";
import { TextField } from "../components";
import { Formik, Form } from "formik";
import * as Yup from "yup";
import { AuthContext } from "../context/auth.context";
import { useRouter } from "next/router";

const Auth = () => {
  const [auth, setAuth] = useState<"signup" | "signin">("signin");
  const { error, isLoading, signIn, signUp, user } = useContext(AuthContext);
  const router = useRouter()

  if (user) router.push('/')
  if (!isLoading) return <>Loading...</>

  const toggleAuth = (state: "signup" | "signin") => {
    setAuth(state);
  };

  const onSubmit = (formData: { email: string; password: string }) => {
    if (auth === "signup") {
      signUp(formData.email, formData.password)
    } else {
      signIn(formData.email, formData.password)
    }
  };

  const validation = Yup.object({
    email: Yup.string()
      .email("Enter valid email")
      .required("Email is required"),
    password: Yup.string()
      .min(6, "6 minimum character")
      .required("Password is required"),
  });

  return (
    <div className="relative flex h-screen w-screen flex-col md:items-center md:justify-center bg-black md:bg-transparent">
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <Image
        src={"https://rb.gy/p2hphi"}
        alt={"bg"}
        fill
        className="object-cover -z-10 !hidden sm:!inline opacity-60"
      />

      <Image
        src={"/logo.svg"}
        alt={"logo"}
        width={70}
        height={70}
        className={" absolute left-4 top-4 cursor-pointer object-contain"}
      />
      <Formik
        initialValues={{ email: "", password: "" }}
        onSubmit={onSubmit}
        validationSchema={validation}
      >
        <Form className="relative mt-24 space-y-8 rounded bg-black/75 py-10 px-6 md:mt-0 md:max-w-md md:px-14">
          <h1 className="text-4xl font-semibold">
            {auth === "signup" ? "Sign Up" : "Sign In"}
          </h1>
          {error && (
            <p className="text-red-500 font-semibold text-center">{error}</p>
          )}
          <div className=" space-y-4">
            <TextField name="email" placeholder="Email" type="text" />
            <TextField name="password" placeholder="Password" type="password" />
          </div>
          <button disabled={isLoading}
            type="submit"
            className="w-full bg-[#E10856] py-3 font-semibold mt-5"
          >
            {isLoading ? 'Loading...' : auth === "signup" ? "Sign Up" : "Sign In"}
          </button>
          {auth === "signin" ? (
            <div className="text-[gray] text-center">
              Not Yet account?{" "}
              <button
                type="button"
                className="text-white hover:underline"
                onClick={() => toggleAuth("signup")}
              >
                Sign Up Now
              </button>
            </div>
          ) : (
            <div className="text-[gray] text-center">
              Already have account?{" "}
              <button
                type="button"
                className="text-white hover:underline"
                onClick={() => toggleAuth("signin")}
              >
                Sign In
              </button>
            </div>
          )}
        </Form>
      </Formik>
    </div>
  );
};

export default Auth;
