import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

const Auth = () => {
  const [auth, setAuth] = useState<"signup" | "signin">("signin");
  const toggleAuth = (state: "signup" | "signin") => {
    setAuth(state);
  };
  return (
    <div className="relative flex h-screen w-screen flex-col md:items-center md:justify-center bg-black md:bg-transparent">
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <Image
        src={"https://rb.gy/p2hphi"}
        alt={"bg"}
        fill
        className="object-cover -z-10 !hidden sm:!inline opacity-60"
      />

      <Image
        src={"/logo.svg"}
        alt={"logo"}
        width={70}
        height={70}
        className={" absolute left-4 top-4 cursor-pointer object-contain"}
      />

      <form className=" relative mt-24 space-y-8 rounded bg-black/75 py-10 px-6 md:mt-0 md:max-w-md md:px-14">
        <h1 className="text-4xl font-semibold">
          {auth === "signup" ? "Sign Up" : "Sign In"}
        </h1>
        <div className=" space-y-4">
          <label className="inline-block w-full">
            <input type="text" placeholder="Email" className="input" />
          </label>
          <label className="inline-block w-full">
            <input type="password" placeholder="Password" className="input" />
          </label>
        </div>
        <button
          type="submit"
          className="w-full bg-[#E10856] py-3 font-semibold"
        >
          {auth === "signup" ? "Sign Up" : "Sign In"}
        </button>

        {auth === "signin" ? (
          <div className="text-[gray] text-center">
            Not Yet account?{" "}
            <button
              type="button"
              className="text-white hover:underline"
              onClick={() => toggleAuth("signup")}
            >
              Sign Up Now
            </button>
          </div>
        ) : (
          <div className="text-[gray] text-center">
            Already have account?{" "}
            <button
              type="button"
              className="text-white hover:underline"
              onClick={() => toggleAuth("signin")}
            >
              Sign In
            </button>
          </div>
        )}
      </form>
    </div>
  );
};

export default Auth;
